#! /bin/sh

cd /usr/local/www/roundcube/plugins/password
rm -f config.inc.php
cp config.inc.php.dist config.inc.php
patch --posix -p1 -i /freebsd-configuration/patches/roundcube/roundcube-password-plugin-config.diff

