#!/bin/sh

# PROVIDE: gateone
# REQUIRE: LOGIN DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name="gateone"
rcvar="${name}_enable"

load_rc_config $name

python_interpreter="/usr/local/bin/python2"
python_major_and_minor_version=$("${python_interpreter}" -V 2>&1 | grep -o "[0-9].[0-9]")

: ${gateone_enable:=NO}
: ${gateone_user:="${name}"}
: ${gateone_group:="${name}"}
: ${gateone_home:="/usr/local/gateone"}
: ${gateone_env:="HOME=\"${gateone_home}\" PATH=\"${PATH}:/usr/local/sbin:/usr/local/bin\" PYTHONPATH=\"${gateone_home}/lib/python${python_major_and_minor_version}/site-packages\""}

procname="${gateone_home}/bin/${name}"
command_interpreter="${python_interpreter}"

command="/usr/sbin/daemon"
command_args="-f ${procname} --settings_dir=\"${gateone_home}/etc/${name}\""

run_rc_command "$1"
