#! /usr/bin/env bash

# OpenLDAP
service slapd restart

# Dovecot
service dovecot restart

# Postfix
service postfix status
service postfix restart 2>&1
service postfix status

# nginx
service nginx restart

