#
# PRODUCTION
#
production:
  main:
    adapter: postgresql
    encoding: unicode
    database: gitlab
    username: gitlab
    password: gitlab_password
    host: localhost
    # load_balancing:
    #   hosts:
    #     - host1.example.com
    #     - host2.example.com
    #   discover:
    #     nameserver: 1.2.3.4
    #     port: 8600
    #     record: secondary.postgresql.service.consul
    #     interval: 300
  ci:
    adapter: postgresql
    encoding: unicode
    database: gitlab
    database_tasks: false
    username: gitlab
    password: gitlab_password
    host: localhost
  # geo:
  #   adapter: postgresql
  #   encoding: unicode
  #   database: gitlabhq_geo_production
  #   username: git
  #   password: "secure password"
  #   host: localhost

#
# Development specific
#
development:
  main:
    adapter: postgresql
    encoding: unicode
    database: gitlabhq_development
    username: postgres
    password: "secure password"
    host: localhost
    variables:
      statement_timeout: 15s
  ci:
    adapter: postgresql
    encoding: unicode
    database: gitlabhq_development
    database_tasks: false
    username: postgres
    password: "secure password"
    host: localhost
    variables:
      statement_timeout: 15s
  # geo:
  #   adapter: postgresql
  #   encoding: unicode
  #   database: gitlabhq_geo_development
  #   username: postgres
  #   password: "secure password"
  #   host: localhost

#
# Staging specific
#
staging:
  main:
    adapter: postgresql
    encoding: unicode
    database: gitlabhq_staging
    username: git
    password: "secure password"
    host: localhost
  ci:
    adapter: postgresql
    encoding: unicode
    database: gitlabhq_staging
    database_tasks: false
    username: git
    password: "secure password"
    host: localhost
  # geo:
  #   adapter: postgresql
  #   encoding: unicode
  #   database: gitlabhq_geo_staging
  #   username: git
  #   password: "secure password"
  #   host: localhost

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test: &test
  main:
    adapter: postgresql
    encoding: unicode
    database: gitlabhq_test
    username: postgres
    password:
    host: localhost
    prepared_statements: false
    reaping_frequency: nil
    variables:
      statement_timeout: 15s
  ci:
    adapter: postgresql
    encoding: unicode
    database: gitlabhq_test
    database_tasks: false
    username: postgres
    password:
    host: localhost
    prepared_statements: false
    reaping_frequency: nil
    variables:
      statement_timeout: 15s
  # geo:
  #   adapter: postgresql
  #   encoding: unicode
  #   database: gitlabhq_geo_test
  #   username: postgres
  #   password:
  #   host: localhost
  #   reaping_frequency: nil
  # embedding:
  #   adapter: postgresql
  #   encoding: unicode
  #   database: gitlabhq_embedding_test
  #   username: postgres
  #   password:
  #   host: localhost
  #   reaping_frequency: nil
