#! /bin/sh

cd /usr/local/etc/dovecot
cp -a example-config/* .
patch --posix -p1 -i /freebsd-configuration/patches/dovecot/dovecot-base-configuration.diff
chown root:dovecot dovecot-sql.conf.ext
chmod 640 dovecot-sql.conf.ext

