#! /bin/sh

cd /etc/pam.d
for file_name in su-password-prompt-pam-system.diff ssh-password-prompt-pam-sshd.diff
do
    patch --posix -p1 -i /freebsd-configuration/patches/password-prompts/${file_name}
done

